# Generated by Django 6.0.5 on 2026-07-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphicaluser',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='graphicaluser',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
